import './globals.css'
import type { Metadata } from 'next'
import { Libre_Baskerville } from 'next/font/google'

const Libre = Libre_Baskerville({
  weight: [ '400', '700' ],
  style: 'normal',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={Libre.className}>{children}</body>
    </html>
  )
}
